-- Columnas de cobertura opcional en cola de emisión RCV (Nexus).
-- Ejecutar en Sis2000 QA antes de sp_pre_emision_automovil_rcv_nexus v2.

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'coberAdicional') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD coberAdicional VARCHAR(2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'tasaPt') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD tasaPt NUMERIC(18, 2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'tasaCa') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD tasaCa NUMERIC(18, 2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'tasaPp') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD tasaPp NUMERIC(18, 2) NULL;

GO
