-- Columnas de cobertura opcional en cola de emisión RCV (Nexus).
-- Ejecutar en Sis2000 QA antes de sp_pre_emision_automovil_rcv_nexus v2.

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'cober_adicional') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD cober_adicional VARCHAR(2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'ptasa_pt') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD ptasa_pt NUMERIC(18, 2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'ptasa_ca') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD ptasa_ca NUMERIC(18, 2) NULL;

IF COL_LENGTH('TMEMISION_AUTOMOVIL_RCV2', 'ptasa_pp') IS NULL
    ALTER TABLE TMEMISION_AUTOMOVIL_RCV2 ADD ptasa_pp NUMERIC(18, 2) NULL;

GO
