-- Pre-emisión personas/funerario (Nexus).
-- Cadena: speeValidatePersonGeneral → contador Nexus → TMEMISION_* → sp_emision_personas_general_nexus
-- nest-api: POST /personas/emission (createEmissionPerson)
